import { v4 as uuidv4 } from 'uuid';
import { User, ServiceCategory, Service, Subscription, Order, SupportTicket, TicketResponse, SimpleCustomer, AdminNotification } from './types';

// Mock users
export const users: User[] = [
  {
    id: 'user-1',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'customer',
    balance: 100,
    createdAt: '2023-01-01T00:00:00Z'
  },
  {
    id: 'user-2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'customer',
    balance: 50,
    createdAt: '2023-01-15T00:00:00Z'
  },
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'admin',
    balance: 0,
    createdAt: '2022-12-01T00:00:00Z'
  }
];

// Service categories
export const categories: ServiceCategory[] = [
  {
    id: 'streaming',
    name: 'Streaming Services',
    description: 'Access to popular streaming platforms',
    order: 1,
    icon: 'tv'
  },
  {
    id: 'gaming',
    name: 'Gaming',
    description: 'Gaming subscriptions and credits',
    order: 2,
    icon: 'gamepad'
  },
  {
    id: 'vpn',
    name: 'VPN Services',
    description: 'Virtual Private Network services',
    order: 3,
    icon: 'shield'
  },
  {
    id: 'productivity',
    name: 'Productivity',
    description: 'Office and productivity tools',
    order: 4,
    icon: 'briefcase'
  },
  {
    id: 'communication',
    name: 'Communication',
    description: 'Communication and social media services',
    order: 5,
    icon: 'message-circle'
  },
  {
    id: 'other',
    name: 'Other Services',
    description: 'Miscellaneous services',
    order: 6,
    icon: 'more-horizontal'
  }
];

// Services/Products data
export const services: Service[] = [
  {
    id: 'service-netflix',
    name: 'Netflix Premium',
    description: 'Netflix Premium subscription with 4K streaming and multiple devices',
    price: 19.99,
    wholesalePrice: 16.99,
    type: 'subscription',
    image: '/images/netflix.png',
    categoryId: 'streaming',
    featured: true,
    deliveryTime: '24 hours',
    availableMonths: [1, 3, 6, 12],
    monthlyPricing: [
      { months: 1, price: 19.99, wholesalePrice: 16.99 },
      { months: 3, price: 53.99, wholesalePrice: 45.99, savings: 5.98 },
      { months: 6, price: 99.99, wholesalePrice: 89.99, savings: 19.95 },
      { months: 12, price: 189.99, wholesalePrice: 169.99, savings: 49.89 }
    ],
    features: [
      '4K Ultra HD streaming',
      'Watch on 4 devices at once',
      'Download titles to watch offline',
      'No ads or commercials'
    ]
  },
  {
    id: 'service-disney',
    name: 'Disney+ Premium',
    description: 'Disney+ streaming service with access to Disney, Pixar, Marvel, Star Wars, and more',
    price: 12.99,
    wholesalePrice: 10.99,
    type: 'subscription',
    image: '/images/disney.png',
    categoryId: 'streaming',
    featured: true,
    deliveryTime: '24 hours',
    availableMonths: [1, 3, 6, 12],
    features: [
      '4K Ultra HD streaming',
      'Watch on 4 devices at once',
      'Download titles to watch offline',
      'Access to Disney, Pixar, Marvel, Star Wars'
    ]
  },
  {
    id: 'service-spotify',
    name: 'Spotify Premium',
    description: 'Spotify Premium subscription with ad-free music listening and offline downloads',
    price: 9.99,
    wholesalePrice: 7.99,
    type: 'subscription',
    image: '/images/spotify.png',
    categoryId: 'streaming',
    deliveryTime: '24 hours',
    availableMonths: [1, 3, 6, 12],
    features: [
      'Ad-free music listening',
      'Offline downloads',
      'High-quality audio',
      'Access to millions of songs'
    ]
  },
  {
    id: 'service-nordvpn',
    name: 'NordVPN',
    description: 'NordVPN subscription for secure and private internet access',
    price: 7.99,
    wholesalePrice: 5.99,
    type: 'subscription',
    image: '/images/nordvpn.png',
    categoryId: 'vpn',
    deliveryTime: 'Instant',
    availableMonths: [1, 12, 24],
    features: [
      'Secure internet access',
      'Private browsing',
      'Access to blocked content',
      'Multiple server locations'
    ]
  },
  {
    id: 'service-expressvpn',
    name: 'ExpressVPN',
    description: 'ExpressVPN subscription for fast and reliable VPN service',
    price: 9.99,
    wholesalePrice: 7.99,
    type: 'subscription',
    image: '/images/expressvpn.png',
    categoryId: 'vpn',
    deliveryTime: 'Instant',
    availableMonths: [1, 6, 12],
    features: [
      'Fast and reliable VPN service',
      'Secure internet access',
      'Private browsing',
      'Multiple server locations'
    ]
  },
  {
    id: 'service-gta5',
    name: 'GTA V Online Credits',
    description: 'Get GTA V Online credits to buy cars, weapons, and more',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'topup',
    image: '/images/gta5.png',
    categoryId: 'gaming',
    deliveryTime: 'Instant',
    value: 500000,
    minQuantity: 1
  },
  {
    id: 'service-fortnite',
    name: 'Fortnite V-Bucks',
    description: 'Get Fortnite V-Bucks to buy skins, emotes, and more',
    price: 7.99,
    wholesalePrice: 5.99,
    type: 'topup',
    image: '/images/fortnite.png',
    categoryId: 'gaming',
    deliveryTime: 'Instant',
    value: 1000,
    minQuantity: 1
  },
  {
    id: 'service-mobile-recharge',
    name: 'Mobile Recharge',
    description: 'Recharge your mobile phone with credits',
    price: 10.00,
    wholesalePrice: 8.00,
    type: 'recharge',
    image: '/images/mobile-recharge.png',
    categoryId: 'recharge',
    deliveryTime: 'Instant',
    value: 10,
    minQuantity: 1
  },
  {
    id: 'service-giftcard-amazon',
    name: 'Amazon Gift Card',
    description: 'Get an Amazon gift card to buy anything on Amazon',
    price: 25.00,
    wholesalePrice: 20.00,
    type: 'giftcard',
    image: '/images/amazon-giftcard.png',
    categoryId: 'giftcard',
    deliveryTime: 'Instant',
    value: 25,
    minQuantity: 1
  },
  {
    id: 'service-office365',
    name: 'Microsoft 365',
    description: 'Access to Microsoft Office suite',
    price: 6.99,
    wholesalePrice: 4.99,
    type: 'subscription',
    image: '/images/office365.png',
    categoryId: 'productivity',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Access to Word, Excel, PowerPoint',
      '1TB OneDrive storage',
      'Premium features',
    ]
  },
  {
    id: 'service-adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    description: 'Access to Adobe Creative Cloud suite',
    price: 29.99,
    wholesalePrice: 24.99,
    type: 'subscription',
    image: '/images/adobe-creative-cloud.png',
    categoryId: 'productivity',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Access to Photoshop, Illustrator, Premiere Pro',
      '100GB cloud storage',
      'Premium fonts',
    ]
  },
  {
    id: 'service-whatsapp-number',
    name: 'WhatsApp Number',
    description: 'Get a virtual WhatsApp number',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'service',
    image: '/images/whatsapp-number.png',
    categoryId: 'communication',
    deliveryTime: 'Instant',
    minQuantity: 1
  },
  {
    id: 'service-instagram-followers',
    name: 'Instagram Followers',
    description: 'Get Instagram followers',
    price: 9.99,
    wholesalePrice: 7.99,
    type: 'service',
    image: '/images/instagram-followers.png',
    categoryId: 'communication',
    deliveryTime: 'Instant',
    minQuantity: 100
  },
  {
    id: 'service-zoom-meeting',
    name: 'Zoom Meeting',
    description: 'Zoom Meeting subscription',
    price: 14.99,
    wholesalePrice: 11.99,
    type: 'subscription',
    image: '/images/zoom-meeting.png',
    categoryId: 'communication',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Host meetings with up to 100 participants',
      'Unlimited meeting duration',
      'Screen sharing',
    ]
  },
  {
    id: 'service-slack-workspace',
    name: 'Slack Workspace',
    description: 'Slack Workspace subscription',
    price: 7.99,
    wholesalePrice: 5.99,
    type: 'subscription',
    image: '/images/slack-workspace.png',
    categoryId: 'communication',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Unlimited channels',
      'Unlimited message history',
      'Guest access',
    ]
  },
  {
    id: 'service-google-one',
    name: 'Google One',
    description: 'Google One subscription',
    price: 1.99,
    wholesalePrice: 1.49,
    type: 'subscription',
    image: '/images/google-one.png',
    categoryId: 'productivity',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      '100GB cloud storage',
      'Google Photos storage',
      'Premium support',
    ]
  },
  {
    id: 'service-youtube-premium',
    name: 'YouTube Premium',
    description: 'YouTube Premium subscription',
    price: 11.99,
    wholesalePrice: 9.99,
    type: 'subscription',
    image: '/images/youtube-premium.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Ad-free videos',
      'Background playback',
      'YouTube Music Premium',
    ]
  },
  {
    id: 'service-hulu',
    name: 'Hulu',
    description: 'Hulu subscription',
    price: 7.99,
    wholesalePrice: 6.49,
    type: 'subscription',
    image: '/images/hulu.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Access to Hulu library',
      'Original series',
      'Live TV',
    ]
  },
  {
    id: 'service-twitch-turbo',
    name: 'Twitch Turbo',
    description: 'Twitch Turbo subscription',
    price: 8.99,
    wholesalePrice: 7.49,
    type: 'subscription',
    image: '/images/twitch-turbo.png',
    categoryId: 'gaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Ad-free viewing',
      'Custom emotes',
      'Extended broadcast storage',
    ]
  },
  {
    id: 'service-playstation-plus',
    name: 'PlayStation Plus',
    description: 'PlayStation Plus subscription',
    price: 9.99,
    wholesalePrice: 8.49,
    type: 'subscription',
    image: '/images/playstation-plus.png',
    categoryId: 'gaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Online multiplayer',
      'Free games each month',
      'Exclusive discounts',
    ]
  },
  {
    id: 'service-xbox-game-pass',
    name: 'Xbox Game Pass',
    description: 'Xbox Game Pass subscription',
    price: 9.99,
    wholesalePrice: 8.49,
    type: 'subscription',
    image: '/images/xbox-game-pass.png',
    categoryId: 'gaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Access to hundreds of games',
      'Exclusive discounts',
      'Day one releases',
    ]
  },
  {
    id: 'service-discord-nitro',
    name: 'Discord Nitro',
    description: 'Discord Nitro subscription',
    price: 9.99,
    wholesalePrice: 8.49,
    type: 'subscription',
    image: '/images/discord-nitro.png',
    categoryId: 'communication',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Animated avatar',
      'Custom tags',
      'Increased upload limit',
    ]
  },
  {
    id: 'service-linkedin-premium',
    name: 'LinkedIn Premium',
    description: 'LinkedIn Premium subscription',
    price: 29.99,
    wholesalePrice: 24.99,
    type: 'subscription',
    image: '/images/linkedin-premium.png',
    categoryId: 'communication',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Unlimited profile views',
      'InMail messages',
      'Online video courses',
    ]
  },
  {
    id: 'service-skillshare',
    name: 'Skillshare',
    description: 'Skillshare subscription',
    price: 19.00,
    wholesalePrice: 15.00,
    type: 'subscription',
    image: '/images/skillshare.png',
    categoryId: 'productivity',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Access to thousands of classes',
      'Offline access',
      'Creative community',
    ]
  },
  {
    id: 'service-canva-pro',
    name: 'Canva Pro',
    description: 'Canva Pro subscription',
    price: 12.99,
    wholesalePrice: 10.99,
    type: 'subscription',
    image: '/images/canva-pro.png',
    categoryId: 'productivity',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Unlimited storage',
      'Premium templates',
      'Brand kit',
    ]
  },
  {
    id: 'service-duolingo-plus',
    name: 'Duolingo Plus',
    description: 'Duolingo Plus subscription',
    price: 6.99,
    wholesalePrice: 5.49,
    type: 'subscription',
    image: '/images/duolingo-plus.png',
    categoryId: 'other',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Ad-free learning',
      'Offline access',
      'Progress quiz',
    ]
  },
  {
    id: 'service-headspace',
    name: 'Headspace',
    description: 'Headspace subscription',
    price: 12.99,
    wholesalePrice: 10.99,
    type: 'subscription',
    image: '/images/headspace.png',
    categoryId: 'other',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Meditation courses',
      'Sleep sounds',
      'Mindfulness exercises',
    ]
  },
  {
    id: 'service-masterclass',
    name: 'Masterclass',
    description: 'Masterclass subscription',
    price: 15.00,
    wholesalePrice: 12.00,
    type: 'subscription',
    image: '/images/masterclass.png',
    categoryId: 'other',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Access to hundreds of classes',
      'Learn from the best',
      'Exclusive content',
    ]
  },
  {
    id: 'service-crunchyroll',
    name: 'Crunchyroll',
    description: 'Crunchyroll subscription',
    price: 7.99,
    wholesalePrice: 6.49,
    type: 'subscription',
    image: '/images/crunchyroll.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Ad-free anime',
      'New episodes shortly after Japan',
      'Access to manga',
    ]
  },
  {
    id: 'service-paramount-plus',
    name: 'Paramount+',
    description: 'Paramount+ subscription',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'subscription',
    image: '/images/paramount-plus.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Live sports',
      'Movies',
    ]
  },
  {
    id: 'service-peacock-premium',
    name: 'Peacock Premium',
    description: 'Peacock Premium subscription',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'subscription',
    image: '/images/peacock-premium.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Live sports',
      'Movies',
    ]
  },
  {
    id: 'service-discovery-plus',
    name: 'Discovery+',
    description: 'Discovery+ subscription',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'subscription',
    image: '/images/discovery-plus.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Exclusive content',
      'Reality TV',
    ]
  },
  {
    id: 'service-starz',
    name: 'Starz',
    description: 'Starz subscription',
    price: 8.99,
    wholesalePrice: 7.49,
    type: 'subscription',
    image: '/images/starz.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-showtime',
    name: 'Showtime',
    description: 'Showtime subscription',
    price: 10.99,
    wholesalePrice: 8.99,
    type: 'subscription',
    image: '/images/showtime.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-epix',
    name: 'Epix',
    description: 'Epix subscription',
    price: 5.99,
    wholesalePrice: 4.99,
    type: 'subscription',
    image: '/images/epix.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-fubo-tv',
    name: 'Fubo TV',
    description: 'Fubo TV subscription',
    price: 64.99,
    wholesalePrice: 54.99,
    type: 'subscription',
    image: '/images/fubo-tv.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Live sports',
      'News',
      'Entertainment',
    ]
  },
  {
    id: 'service-sling-tv',
    name: 'Sling TV',
    description: 'Sling TV subscription',
    price: 35.00,
    wholesalePrice: 29.00,
    type: 'subscription',
    image: '/images/sling-tv.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Live TV',
      'News',
      'Entertainment',
    ]
  },
  {
    id: 'service-directv-stream',
    name: 'DirecTV Stream',
    description: 'DirecTV Stream subscription',
    price: 69.99,
    wholesalePrice: 59.99,
    type: 'subscription',
    image: '/images/directv-stream.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Live TV',
      'News',
      'Entertainment',
    ]
  },
  {
    id: 'service-hbo-max',
    name: 'HBO Max',
    description: 'HBO Max subscription',
    price: 14.99,
    wholesalePrice: 12.99,
    type: 'subscription',
    image: '/images/hbo-max.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-apple-tv-plus',
    name: 'Apple TV+',
    description: 'Apple TV+ subscription',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'subscription',
    image: '/images/apple-tv-plus.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-britbox',
    name: 'BritBox',
    description: 'BritBox subscription',
    price: 6.99,
    wholesalePrice: 5.49,
    type: 'subscription',
    image: '/images/britbox.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'British TV',
      'Original series',
      'Movies',
    ]
  },
  {
    id: 'service-acorn-tv',
    name: 'Acorn TV',
    description: 'Acorn TV subscription',
    price: 5.99,
    wholesalePrice: 4.99,
    type: 'subscription',
    image: '/images/acorn-tv.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'British TV',
      'Original series',
      'Movies',
    ]
  },
  {
    id: 'service-criterion-channel',
    name: 'Criterion Channel',
    description: 'Criterion Channel subscription',
    price: 10.99,
    wholesalePrice: 8.99,
    type: 'subscription',
    image: '/images/criterion-channel.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Classic movies',
      'Independent films',
      'Foreign films',
    ]
  },
  {
    id: 'service-mubi',
    name: 'Mubi',
    description: 'Mubi subscription',
    price: 10.99,
    wholesalePrice: 8.99,
    type: 'subscription',
    image: '/images/mubi.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Curated films',
      'Independent films',
      'Foreign films',
    ]
  },
  {
    id: 'service-kanopy',
    name: 'Kanopy',
    description: 'Kanopy subscription',
    price: 0.00,
    wholesalePrice: 0.00,
    type: 'subscription',
    image: '/images/kanopy.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Free movies',
      'Documentaries',
      'Educational films',
    ]
  },
  {
    id: 'service-criterion-channel',
    name: 'The Criterion Channel',
    description: 'The Criterion Channel subscription',
    price: 10.99,
    wholesalePrice: 8.99,
    type: 'subscription',
    image: '/images/criterion-channel.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Classic and contemporary films',
      'Director interviews',
      'Exclusive content',
    ]
  },
  {
    id: 'service-shudder',
    name: 'Shudder',
    description: 'Shudder subscription',
    price: 5.99,
    wholesalePrice: 4.99,
    type: 'subscription',
    image: '/images/shudder.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Horror movies',
      'Thrillers',
      'Suspense',
    ]
  },
  {
    id: 'service-amc-plus',
    name: 'AMC+',
    description: 'AMC+ subscription',
    price: 8.99,
    wholesalePrice: 7.49,
    type: 'subscription',
    image: '/images/amc-plus.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-curiosity-stream',
    name: 'Curiosity Stream',
    description: 'Curiosity Stream subscription',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'subscription',
    image: '/images/curiosity-stream.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Documentaries',
      'Science',
      'History',
    ]
  },
  {
    id: 'service-discovery-plus',
    name: 'Discovery+',
    description: 'Discovery+ subscription',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'subscription',
    image: '/images/discovery-plus.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Reality TV',
      'True crime',
      'Home improvement',
    ]
  },
  {
    id: 'service-hbo-max',
    name: 'HBO Max',
    description: 'HBO Max subscription',
    price: 14.99,
    wholesalePrice: 12.99,
    type: 'subscription',
    image: '/images/hbo-max.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-disney-plus',
    name: 'Disney+',
    description: 'Disney+ subscription',
    price: 7.99,
    wholesalePrice: 6.49,
    type: 'subscription',
    image: '/images/disney-plus.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-netflix',
    name: 'Netflix',
    description: 'Netflix subscription',
    price: 8.99,
    wholesalePrice: 7.49,
    type: 'subscription',
    image: '/images/netflix.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-hulu',
    name: 'Hulu',
    description: 'Hulu subscription',
    price: 5.99,
    wholesalePrice: 4.99,
    type: 'subscription',
    image: '/images/hulu.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-amazon-prime-video',
    name: 'Amazon Prime Video',
    description: 'Amazon Prime Video subscription',
    price: 8.99,
    wholesalePrice: 7.49,
    type: 'subscription',
    image: '/images/amazon-prime-video.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-paramount-plus',
    name: 'Paramount+',
    description: 'Paramount+ subscription',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'subscription',
    image: '/images/paramount-plus.png',
    categoryId: 'streaming',
    deliveryTime: 'Instant',
    availableMonths: [1, 12],
    features: [
      'Original series',
      'Movies',
      'Exclusive content',
    ]
  },
  {
    id: 'service-peacock-premium',
    name: 'Peacock Premium',
    description: 'Peacock Premium subscription',
    price: 4.99,
    wholesalePrice: 3.99,
    type: 'subscription',
    image: '/images/peacock-premium.png',
    categoryId: 'streaming',
