// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbirhrlxslphtcuhijvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiaXJocmx4c2xwaHRjdWhpanZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzY1ODMsImV4cCI6MjA1ODMxMjU4M30.MzUMh-jkooMQaeRr2ZgF4kYSGSebXkY30IXoqLoJM_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);